<?php global $site_url;?>
<div class="content-bg-wrap"></div>


<!-- Header Standard Landing  -->

<div class="header--standard header--standard-landing" id="header--standard">
	<div class="container">
		<div class="header--standard-wrap">

			<a href="#" class="logo">
				<div class="img-wrap">
					<img src="<?=$site_url?>assets/sitio/img/logo.png" alt="Olympus">
					<img src="<?=$site_url?>assets/sitio/img/logo-colored-small.png" alt="Olympus" class="logo-colored">
				</div>
				<div class="title-block">
					<h6 class="logo-title">Uta</h6>
					<div class="sub-title">Sistema de Calificaciones</div>
				</div>
			</a>

			<a href="#" class="open-responsive-menu js-open-responsive-menu">
				<svg class="olymp-menu-icon"><use xlink:href="<?=$site_url?>assets/sitio/svg-icons/sprites/icons.svg#olymp-menu-icon"></use></svg>
			</a>

			<div class="nav nav-pills nav1 header-menu">
			</div>
		</div>
	</div>
</div>

<!-- ... end Header Standard Landing  -->
<div class="header-spacer--standard"></div>

<div class="container">
	<div class="row display-flex">
		<div class="col col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">
			<div class="landing-content">
				<h1>Bienvenido al nuevo SITO</h1>
				<p>Hemos echo unos cambios en el antiguo sistema de calificaciones para hacerlo
					mas agradable a sus usuarios.
				</p>
			</div>
		</div>

		<div class="col col-xl-5 col-lg-6 col-md-12 col-sm-12 col-12">

			<!-- Login-Registration Form  -->

			<div class="registration-login-form">
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
					<li class="nav-item">
						<a class="nav-link active" data-toggle="tab" href="#home" role="tab">
							<svg class="olymp-login-icon"><use xlink:href="<?=$site_url?>/assets/sitio/svg-icons/sprites/icons.svg#olymp-login-icon"></use></svg>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" data-toggle="tab" href="#profile" role="tab">
							<svg class="olymp-register-icon"><use xlink:href="<?=$site_url?>/assets/sitio/svg-icons/sprites/icons.svg#olymp-register-icon"></use></svg>
						</a>
					</li>
				</ul>

				<!-- Tab panes -->
				<div class="tab-content">
					<div class="tab-pane active" id="home" role="tabpanel" data-mh="log-tab">
						<div class="title h6">Registrate en SITO</div>

						<form class="content form-ajax" data-url="Regristrar">
							<div class="row">
								<div class="col col-12 col-xl-6 col-lg-6 col-md-6 col-sm-12">
									<div class="form-group label-floating is-empty">
										<label class="control-label">Nombre</label>
										<input class="form-control" name="datos[Nombre]" required="" placeholder="" type="text">
									</div>
								</div>
								<div class="col col-12 col-xl-6 col-lg-6 col-md-6 col-sm-12">
									<div class="form-group label-floating is-empty">
										<label class="control-label">Apellido</label>
										<input class="form-control" name="datos[Apellidos]" required="" placeholder="" type="text">
									</div>
								</div>
								<div class="col col-12 col-xl-12 col-lg-12 col-md-12 col-sm-12">
									<div class="form-group label-floating is-empty">
										<label class="control-label">Correo Electronico</label>
										<input class="form-control" name="datos[Correo_Electronico]" required="" placeholder="" type="email">
									</div>
									<div class="form-group label-floating is-empty">
										<label class="control-label">Contraseña</label>
										<input class="form-control" name="datos[Contraseña]" required="" placeholder="" type="password">
									</div>

									<div class="remember">
										<div class="checkbox">
											<label>
												<input name="optionsCheckboxes" type="checkbox">
												Acepto los <a href="#">Terminos y condiciones</a> del sitio web
											</label>
										</div>
									</div>
									<input class="btn btn-purple btn-lg full-width" type="submit" name="" value="Completar el Registro">
								</div>
							</div>
						</form>
					</div>

					<div class="tab-pane" id="profile" role="tabpanel" data-mh="log-tab">
						<div class="title h6">Ingresa con tu usuarios</div>
						<form class="content form-ajax" data-url="Ingresar">
							<div class="row">
								<div class="col col-12 col-xl-12 col-lg-12 col-md-12 col-sm-12">
									<div class="form-group label-floating is-empty">
										<label class="control-label required">Correo Electronico</label>
										<input class="form-control" required="" placeholder="" type="email">
									</div>
									<div class="form-group label-floating is-empty">
										<label class="control-label">Contraseña</label>
										<input class="form-control" placeholder="" type="password">
									</div>

									<div class="remember">

										<div class="checkbox">
											<label>
												<input name="optionsCheckboxes" type="checkbox">
												Recordarme
											</label>
										</div>
										<a href="#" class="forgot">Olvidaste tu contraseña?</a>
									</div>
									<input type="submit" name="" class="btn btn-lg btn-primary full-width" value="Ingresar">
									<p>No tienes ninguna cuenta? <a href="#">Regristrate ahora! </a>es muy facil y te ayudara a tener mejor control sobre
									tu informacion.</p>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>

			<!-- ... end Login-Registration Form  -->		</div>
	</div>
</div>
